name: WelcomeMan
main: me.joris.welcomeman.WelcomeCore
version: 1.0
descripton: Greets players

author: Joris

commands:
    changename:
      description: Change the username
      usage: /<command> <name>